services:
  postgres:
    image: postgres:16
    container_name: janus_postgres
    environment:
      POSTGRES_USER: janus
      POSTGRES_PASSWORD: janus_password
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - janus_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U janus -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: janus_airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://janus:janus_password@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: ["bash","-lc","airflow db migrate && airflow users create --username airflow --password airflow --firstname Air --lastname Flow --role Admin --email airflow@example.com || true"]

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: janus_airflow_webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://janus:janus_password@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: ["bash","-lc","airflow webserver"]

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: janus_airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://janus:janus_password@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: ["bash","-lc","airflow scheduler"]

volumes:
  janus_pgdata:
